language: generic

before_install:
- mkdir -p ../goluwa && wget 'http://put.nu/files/VHw8LjC.dat' -O ../goluwa/goluwa

script:
- |
  paths=($(git -C $TRAVIS_BUILD_DIR diff --name-only $TRAVIS_COMMIT_RANGE))
  echo $paths
  paths=("${paths[@]/#/$TRAVIS_BUILD_DIR/}")
  sh ../goluwa/goluwa cli --gluacheck $(printf '%s,' "${paths[@]}")
